<?php
namespace Pixelbrackets\RalColorChart;

class RalColorChart
{
    /**
     * The complete list of RAL Classic Colors
     *
     * @var array
     */
    protected $colors = [
        [
            'number' => 'RAL 1000',
            'rangeindex' => '1',
            'nameEnglish' => 'Green beige',
            'nameGerman' => 'Grünbeige',
            'hex' => 'CDBA88',
        ],
        [
            'number' => 'RAL 1001',
            'rangeindex' => '1',
            'nameEnglish' => 'Beige',
            'nameGerman' => 'Beige',
            'hex' => 'D0B084',
        ],
        [
            'number' => 'RAL 1002',
            'rangeindex' => '1',
            'nameEnglish' => 'Sand yellow',
            'nameGerman' => 'Sandgelb',
            'hex' => 'D2AA6D',
        ],
        [
            'number' => 'RAL 1003',
            'rangeindex' => '1',
            'nameEnglish' => 'Signal yellow',
            'nameGerman' => 'Signalgelb',
            'hex' => 'F9A800',
        ],
        [
            'number' => 'RAL 1004',
            'rangeindex' => '1',
            'nameEnglish' => 'Golden yellow',
            'nameGerman' => 'Goldgelb',
            'hex' => 'E49E00',
        ],
        [
            'number' => 'RAL 1005',
            'rangeindex' => '1',
            'nameEnglish' => 'Honey yellow',
            'nameGerman' => 'Honiggelb',
            'hex' => 'CB8E00',
        ],
        [
            'number' => 'RAL 1006',
            'rangeindex' => '1',
            'nameEnglish' => 'Maize yellow',
            'nameGerman' => 'Maisgelb',
            'hex' => 'E29000',
        ],
        [
            'number' => 'RAL 1007',
            'rangeindex' => '1',
            'nameEnglish' => 'Daffodil yellow',
            'nameGerman' => 'Narzissengelb',
            'hex' => 'E88C00',
        ],
        [
            'number' => 'RAL 1011',
            'rangeindex' => '1',
            'nameEnglish' => 'Brown beige',
            'nameGerman' => 'Braunbeige',
            'hex' => 'AF804F',
        ],
        [
            'number' => 'RAL 1012',
            'rangeindex' => '1',
            'nameEnglish' => 'Lemon yellow',
            'nameGerman' => 'Zitronengelb',
            'hex' => 'DDAF27',
        ],
        [
            'number' => 'RAL 1013',
            'rangeindex' => '1',
            'nameEnglish' => 'Oyster white',
            'nameGerman' => 'Perlweiß',
            'hex' => 'E3D9C6',
        ],
        [
            'number' => 'RAL 1014',
            'rangeindex' => '1',
            'nameEnglish' => 'Ivory',
            'nameGerman' => 'Elfenbein',
            'hex' => 'DDC49A',
        ],
        [
            'number' => 'RAL 1015',
            'rangeindex' => '1',
            'nameEnglish' => 'Light ivory / Gaz\'s Beige',
            'nameGerman' => 'Hellelfenbein',
            'hex' => 'E6D2B5',
        ],
        [
            'number' => 'RAL 1016',
            'rangeindex' => '1',
            'nameEnglish' => 'Sulfur yellow',
            'nameGerman' => 'Schwefelgelb',
            'hex' => 'F1DD38',
        ],
        [
            'number' => 'RAL 1017',
            'rangeindex' => '1',
            'nameEnglish' => 'Saffron yellow',
            'nameGerman' => 'Safrangelb',
            'hex' => 'F6A950',
        ],
        [
            'number' => 'RAL 1018',
            'rangeindex' => '1',
            'nameEnglish' => 'Zinc yellow',
            'nameGerman' => 'Zinkgelb',
            'hex' => 'FACA30',
        ],
        [
            'number' => 'RAL 1019',
            'rangeindex' => '1',
            'nameEnglish' => 'Grey beige',
            'nameGerman' => 'Graubeige',
            'hex' => 'A48F7A',
        ],
        [
            'number' => 'RAL 1020',
            'rangeindex' => '1',
            'nameEnglish' => 'Olive yellow',
            'nameGerman' => 'Olivgelb',
            'hex' => 'A08F65',
        ],
        [
            'number' => 'RAL 1021',
            'rangeindex' => '1',
            'nameEnglish' => 'Rape yellow',
            'nameGerman' => 'Rapsgelb',
            'hex' => 'F6B600',
        ],
        [
            'number' => 'RAL 1023',
            'rangeindex' => '1',
            'nameEnglish' => 'Traffic yellow',
            'nameGerman' => 'Verkehrsgelb',
            'hex' => 'F7B500',
        ],
        [
            'number' => 'RAL 1024',
            'rangeindex' => '1',
            'nameEnglish' => 'Ochre yellow',
            'nameGerman' => 'Ockergelb',
            'hex' => 'BA8F4C',
        ],
        [
            'number' => 'RAL 1026',
            'rangeindex' => '1',
            'nameEnglish' => 'Luminous yellow',
            'nameGerman' => 'Leuchtgelb',
            'hex' => 'FFFF00',
        ],
        [
            'number' => 'RAL 1027',
            'rangeindex' => '1',
            'nameEnglish' => 'Curry',
            'nameGerman' => 'Currygelb',
            'hex' => 'A77F0E',
        ],
        [
            'number' => 'RAL 1028',
            'rangeindex' => '1',
            'nameEnglish' => 'Melon yellow',
            'nameGerman' => 'Melonengelb',
            'hex' => 'FF9B00',
        ],
        [
            'number' => 'RAL 1032',
            'rangeindex' => '1',
            'nameEnglish' => 'Broom yellow',
            'nameGerman' => 'Ginstergelb',
            'hex' => 'E2A300',
        ],
        [
            'number' => 'RAL 1033',
            'rangeindex' => '1',
            'nameEnglish' => 'Dahlia yellow',
            'nameGerman' => 'Dahliengelb',
            'hex' => 'F99A1C',
        ],
        [
            'number' => 'RAL 1034',
            'rangeindex' => '1',
            'nameEnglish' => 'Pastel yellow',
            'nameGerman' => 'Pastellgelb',
            'hex' => 'EB9C52',
        ],
        [
            'number' => 'RAL 1035',
            'rangeindex' => '1',
            'nameEnglish' => 'Pearl beige',
            'nameGerman' => 'Perlbeige',
            'hex' => '908370',
        ],
        [
            'number' => 'RAL 1036',
            'rangeindex' => '1',
            'nameEnglish' => 'Pearl gold',
            'nameGerman' => 'Perlgold',
            'hex' => '80643F',
        ],
        [
            'number' => 'RAL 1037',
            'rangeindex' => '1',
            'nameEnglish' => 'Sun yellow',
            'nameGerman' => 'Sonnengelb',
            'hex' => 'F09200',
        ],
        [
            'number' => 'RAL 2000',
            'rangeindex' => '2',
            'nameEnglish' => 'Yellow orange',
            'nameGerman' => 'Gelborange',
            'hex' => 'DD7907',
        ],
        [
            'number' => 'RAL 2001',
            'rangeindex' => '2',
            'nameEnglish' => 'Red orange',
            'nameGerman' => 'Rotorange',
            'hex' => 'BE4E20',
        ],
        [
            'number' => 'RAL 2002',
            'rangeindex' => '2',
            'nameEnglish' => 'Vermillion',
            'nameGerman' => 'Blutorange',
            'hex' => 'C63927',
        ],
        [
            'number' => 'RAL 2003',
            'rangeindex' => '2',
            'nameEnglish' => 'Pastel orange',
            'nameGerman' => 'Pastellorange',
            'hex' => 'FA842B',
        ],
        [
            'number' => 'RAL 2004',
            'rangeindex' => '2',
            'nameEnglish' => 'Pure orange',
            'nameGerman' => 'Reinorange',
            'hex' => 'E75B12',
        ],
        [
            'number' => 'RAL 2005',
            'rangeindex' => '2',
            'nameEnglish' => 'Luminous orange',
            'nameGerman' => 'Leuchtorange',
            'hex' => 'FF2300',
        ],
        [
            'number' => 'RAL 2007',
            'rangeindex' => '2',
            'nameEnglish' => 'Luminous bright orange',
            'nameGerman' => 'Leuchthellorange',
            'hex' => 'FFA421',
        ],
        [
            'number' => 'RAL 2008',
            'rangeindex' => '2',
            'nameEnglish' => 'Bright red orange',
            'nameGerman' => 'Hellrotorange',
            'hex' => 'F3752C',
        ],
        [
            'number' => 'RAL 2009',
            'rangeindex' => '2',
            'nameEnglish' => 'Traffic orange',
            'nameGerman' => 'Verkehrsorange',
            'hex' => 'E15501',
        ],
        [
            'number' => 'RAL 2010',
            'rangeindex' => '2',
            'nameEnglish' => 'Signal orange',
            'nameGerman' => 'Signalorange',
            'hex' => 'D4652F',
        ],
        [
            'number' => 'RAL 2011',
            'rangeindex' => '2',
            'nameEnglish' => 'Deep orange',
            'nameGerman' => 'Tieforange',
            'hex' => 'EC7C25',
        ],
        [
            'number' => 'RAL 2012',
            'rangeindex' => '2',
            'nameEnglish' => 'Salmon orange',
            'nameGerman' => 'Lachsorange',
            'hex' => 'DB6A50',
        ],
        [
            'number' => 'RAL 2013',
            'rangeindex' => '2',
            'nameEnglish' => 'Pearl orange',
            'nameGerman' => 'Perlorange',
            'hex' => '954527',
        ],
        [
            'number' => 'RAL 3000',
            'rangeindex' => '3',
            'nameEnglish' => 'Flame red',
            'nameGerman' => 'Feuerrot',
            'hex' => 'AB2524',
        ],
        [
            'number' => 'RAL 3001',
            'rangeindex' => '3',
            'nameEnglish' => 'Signal red',
            'nameGerman' => 'Signalrot',
            'hex' => 'A02128',
        ],
        [
            'number' => 'RAL 3002',
            'rangeindex' => '3',
            'nameEnglish' => 'Carmine red',
            'nameGerman' => 'Karminrot',
            'hex' => 'A1232B',
        ],
        [
            'number' => 'RAL 3003',
            'rangeindex' => '3',
            'nameEnglish' => 'Ruby red',
            'nameGerman' => 'Rubinrot',
            'hex' => '8D1D2C',
        ],
        [
            'number' => 'RAL 3004',
            'rangeindex' => '3',
            'nameEnglish' => 'Purple red',
            'nameGerman' => 'Purpurrot',
            'hex' => '701F29',
        ],
        [
            'number' => 'RAL 3005',
            'rangeindex' => '3',
            'nameEnglish' => 'Wine red',
            'nameGerman' => 'Weinrot',
            'hex' => '5E2028',
        ],
        [
            'number' => 'RAL 3007',
            'rangeindex' => '3',
            'nameEnglish' => 'Black red',
            'nameGerman' => 'Schwarzrot',
            'hex' => '402225',
        ],
        [
            'number' => 'RAL 3009',
            'rangeindex' => '3',
            'nameEnglish' => 'Oxide red',
            'nameGerman' => 'Oxidrot',
            'hex' => '703731',
        ],
        [
            'number' => 'RAL 3011',
            'rangeindex' => '3',
            'nameEnglish' => 'Brown red',
            'nameGerman' => 'Braunrot',
            'hex' => '7E292C',
        ],
        [
            'number' => 'RAL 3012',
            'rangeindex' => '3',
            'nameEnglish' => 'Beige red',
            'nameGerman' => 'Beigerot',
            'hex' => 'CB8D73',
        ],
        [
            'number' => 'RAL 3013',
            'rangeindex' => '3',
            'nameEnglish' => 'Tomato red',
            'nameGerman' => 'Tomatenrot',
            'hex' => '9C322E',
        ],
        [
            'number' => 'RAL 3014',
            'rangeindex' => '3',
            'nameEnglish' => 'Antique pink',
            'nameGerman' => 'Altrosa',
            'hex' => 'D47479',
        ],
        [
            'number' => 'RAL 3015',
            'rangeindex' => '3',
            'nameEnglish' => 'Light pink',
            'nameGerman' => 'Hellrosa',
            'hex' => 'E1A6AD',
        ],
        [
            'number' => 'RAL 3016',
            'rangeindex' => '3',
            'nameEnglish' => 'Coral red',
            'nameGerman' => 'Korallenrot',
            'hex' => 'AC4034',
        ],
        [
            'number' => 'RAL 3017',
            'rangeindex' => '3',
            'nameEnglish' => 'Rose',
            'nameGerman' => 'Rosé',
            'hex' => 'D3545F',
        ],
        [
            'number' => 'RAL 3018',
            'rangeindex' => '3',
            'nameEnglish' => 'Strawberry red',
            'nameGerman' => 'Erdbeerrot',
            'hex' => 'D14152',
        ],
        [
            'number' => 'RAL 3020',
            'rangeindex' => '3',
            'nameEnglish' => 'Traffic red',
            'nameGerman' => 'Verkehrsrot',
            'hex' => 'C1121C',
        ],
        [
            'number' => 'RAL 3022',
            'rangeindex' => '3',
            'nameEnglish' => 'Salmon pink',
            'nameGerman' => 'Lachsrot',
            'hex' => 'D56D56',
        ],
        [
            'number' => 'RAL 3024',
            'rangeindex' => '3',
            'nameEnglish' => 'Luminous red',
            'nameGerman' => 'Leuchtrot',
            'hex' => 'F70000',
        ],
        [
            'number' => 'RAL 3026',
            'rangeindex' => '3',
            'nameEnglish' => 'Luminous bright red',
            'nameGerman' => 'Leuchthellrot',
            'hex' => 'FF0000',
        ],
        [
            'number' => 'RAL 3027',
            'rangeindex' => '3',
            'nameEnglish' => 'Raspberry red',
            'nameGerman' => 'Himbeerrot',
            'hex' => 'B42041',
        ],
        [
            'number' => 'RAL 3028',
            'rangeindex' => '3',
            'nameEnglish' => 'Pure red',
            'nameGerman' => 'Reinrot',
            'hex' => 'E72512',
        ],
        [
            'number' => 'RAL 3031',
            'rangeindex' => '3',
            'nameEnglish' => 'Orient red',
            'nameGerman' => 'Orientrot',
            'hex' => 'AC323B',
        ],
        [
            'number' => 'RAL 3032',
            'rangeindex' => '3',
            'nameEnglish' => 'Pearl ruby red',
            'nameGerman' => 'Perlrubinrot',
            'hex' => '711521',
        ],
        [
            'number' => 'RAL 3033',
            'rangeindex' => '3',
            'nameEnglish' => 'Pearl pink',
            'nameGerman' => 'Perlrosa',
            'hex' => 'B24C43',
        ],
        [
            'number' => 'RAL 4001',
            'rangeindex' => '4',
            'nameEnglish' => 'Red lilac',
            'nameGerman' => 'Rotlila',
            'hex' => '8A5A83',
        ],
        [
            'number' => 'RAL 4002',
            'rangeindex' => '4',
            'nameEnglish' => 'Red violet',
            'nameGerman' => 'Rotviolett',
            'hex' => '933D50',
        ],
        [
            'number' => 'RAL 4003',
            'rangeindex' => '4',
            'nameEnglish' => 'Heather violet',
            'nameGerman' => 'Erikaviolett',
            'hex' => 'D15B8F',
        ],
        [
            'number' => 'RAL 4004',
            'rangeindex' => '4',
            'nameEnglish' => 'Claret violet',
            'nameGerman' => 'Bordeauxviolett',
            'hex' => '691639',
        ],
        [
            'number' => 'RAL 4005',
            'rangeindex' => '4',
            'nameEnglish' => 'Blue lilac',
            'nameGerman' => 'Blaulila',
            'hex' => '83639D',
        ],
        [
            'number' => 'RAL 4006',
            'rangeindex' => '4',
            'nameEnglish' => 'Traffic purple',
            'nameGerman' => 'Verkehrspurpur',
            'hex' => '992572',
        ],
        [
            'number' => 'RAL 4007',
            'rangeindex' => '4',
            'nameEnglish' => 'Purple violet',
            'nameGerman' => 'Purpurviolett',
            'hex' => '4A203B',
        ],
        [
            'number' => 'RAL 4008',
            'rangeindex' => '4',
            'nameEnglish' => 'Signal violet',
            'nameGerman' => 'Signalviolett',
            'hex' => '904684',
        ],
        [
            'number' => 'RAL 4009',
            'rangeindex' => '4',
            'nameEnglish' => 'Pastel violet',
            'nameGerman' => 'Pastellviolett',
            'hex' => 'A38995',
        ],
        [
            'number' => 'RAL 4010',
            'rangeindex' => '4',
            'nameEnglish' => 'Telemagenta',
            'nameGerman' => 'Telemagenta',
            'hex' => 'C63678',
        ],
        [
            'number' => 'RAL 4011',
            'rangeindex' => '4',
            'nameEnglish' => 'Pearl violet',
            'nameGerman' => 'Perlviolett',
            'hex' => '8773A1',
        ],
        [
            'number' => 'RAL 4012',
            'rangeindex' => '4',
            'nameEnglish' => 'Pearl blackberry',
            'nameGerman' => 'Perlbrombeer',
            'hex' => '6B6880',
        ],
        [
            'number' => 'RAL 5000',
            'rangeindex' => '5',
            'nameEnglish' => 'Violet blue',
            'nameGerman' => 'Violettblau',
            'hex' => '384C70',
        ],
        [
            'number' => 'RAL 5001',
            'rangeindex' => '5',
            'nameEnglish' => 'Green blue',
            'nameGerman' => 'Grünblau',
            'hex' => '1F4764',
        ],
        [
            'number' => 'RAL 5002',
            'rangeindex' => '5',
            'nameEnglish' => 'Ultramarine blue',
            'nameGerman' => 'Ultramarinblau',
            'hex' => '2B2C7C',
        ],
        [
            'number' => 'RAL 5003',
            'rangeindex' => '5',
            'nameEnglish' => 'Sapphire blue',
            'nameGerman' => 'Saphirblau',
            'hex' => '2A3756',
        ],
        [
            'number' => 'RAL 5004',
            'rangeindex' => '5',
            'nameEnglish' => 'Black blue',
            'nameGerman' => 'Schwarzblau',
            'hex' => '1D1F2A',
        ],
        [
            'number' => 'RAL 5005',
            'rangeindex' => '5',
            'nameEnglish' => 'Signal blue',
            'nameGerman' => 'Signalblau',
            'hex' => '154889',
        ],
        [
            'number' => 'RAL 5007',
            'rangeindex' => '5',
            'nameEnglish' => 'Brilliant blue',
            'nameGerman' => 'Brillantblau',
            'hex' => '41678D',
        ],
        [
            'number' => 'RAL 5008',
            'rangeindex' => '5',
            'nameEnglish' => 'Grey blue',
            'nameGerman' => 'Graublau',
            'hex' => '313C48',
        ],
        [
            'number' => 'RAL 5009',
            'rangeindex' => '5',
            'nameEnglish' => 'Azure blue',
            'nameGerman' => 'Azurblau',
            'hex' => '2E5978',
        ],
        [
            'number' => 'RAL 5010',
            'rangeindex' => '5',
            'nameEnglish' => 'Gentian blue',
            'nameGerman' => 'Enzianblau',
            'hex' => '13447C',
        ],
        [
            'number' => 'RAL 5011',
            'rangeindex' => '5',
            'nameEnglish' => 'Steel blue',
            'nameGerman' => 'Stahlblau',
            'hex' => '232C3F',
        ],
        [
            'number' => 'RAL 5012',
            'rangeindex' => '5',
            'nameEnglish' => 'Light blue',
            'nameGerman' => 'Lichtblau',
            'hex' => '3481B8',
        ],
        [
            'number' => 'RAL 5013',
            'rangeindex' => '5',
            'nameEnglish' => 'Cobalt blue',
            'nameGerman' => 'Kobaltblau',
            'hex' => '232D53',
        ],
        [
            'number' => 'RAL 5014',
            'rangeindex' => '5',
            'nameEnglish' => 'Pigeon blue',
            'nameGerman' => 'Taubenblau',
            'hex' => '6C7C98',
        ],
        [
            'number' => 'RAL 5015',
            'rangeindex' => '5',
            'nameEnglish' => 'Sky blue',
            'nameGerman' => 'Himmelblau',
            'hex' => '2874B2',
        ],
        [
            'number' => 'RAL 5017',
            'rangeindex' => '5',
            'nameEnglish' => 'Traffic blue',
            'nameGerman' => 'Verkehrsblau',
            'hex' => '0E518D',
        ],
        [
            'number' => 'RAL 5018',
            'rangeindex' => '5',
            'nameEnglish' => 'Turquoise blue',
            'nameGerman' => 'Türkisblau',
            'hex' => '21888F',
        ],
        [
            'number' => 'RAL 5019',
            'rangeindex' => '5',
            'nameEnglish' => 'Capri blue',
            'nameGerman' => 'Capriblau',
            'hex' => '1A5784',
        ],
        [
            'number' => 'RAL 5020',
            'rangeindex' => '5',
            'nameEnglish' => 'Ocean blue',
            'nameGerman' => 'Ozeanblau',
            'hex' => '0B4151',
        ],
        [
            'number' => 'RAL 5021',
            'rangeindex' => '5',
            'nameEnglish' => 'Water blue',
            'nameGerman' => 'Wasserblau',
            'hex' => '07737A',
        ],
        [
            'number' => 'RAL 5022',
            'rangeindex' => '5',
            'nameEnglish' => 'Night blue',
            'nameGerman' => 'Nachtblau',
            'hex' => '2F2A5A',
        ],
        [
            'number' => 'RAL 5023',
            'rangeindex' => '5',
            'nameEnglish' => 'Distant blue',
            'nameGerman' => 'Fernblau',
            'hex' => '4D668E',
        ],
        [
            'number' => 'RAL 5024',
            'rangeindex' => '5',
            'nameEnglish' => 'Pastel blue',
            'nameGerman' => 'Pastellblau',
            'hex' => '6A93B0',
        ],
        [
            'number' => 'RAL 5025',
            'rangeindex' => '5',
            'nameEnglish' => 'Pearl Gentian blue',
            'nameGerman' => 'Perlenzian',
            'hex' => '296478',
        ],
        [
            'number' => 'RAL 5026',
            'rangeindex' => '5',
            'nameEnglish' => 'Pearl night blue',
            'nameGerman' => 'Perlnachtblau',
            'hex' => '102C54',
        ],
        [
            'number' => 'RAL 6000',
            'rangeindex' => '6',
            'nameEnglish' => 'Patina green',
            'nameGerman' => 'Patinagrün',
            'hex' => '327662',
        ],
        [
            'number' => 'RAL 6001',
            'rangeindex' => '6',
            'nameEnglish' => 'Emerald green',
            'nameGerman' => 'Smaragdgrün',
            'hex' => '28713E',
        ],
        [
            'number' => 'RAL 6002',
            'rangeindex' => '6',
            'nameEnglish' => 'Leaf green',
            'nameGerman' => 'Laubgrün',
            'hex' => '276235',
        ],
        [
            'number' => 'RAL 6003',
            'rangeindex' => '6',
            'nameEnglish' => 'olive green',
            'nameGerman' => 'Olivgrün',
            'hex' => '4B573E',
        ],
        [
            'number' => 'RAL 6004',
            'rangeindex' => '6',
            'nameEnglish' => 'Blue green',
            'nameGerman' => 'Blaugrün',
            'hex' => '0E4243',
        ],
        [
            'number' => 'RAL 6005',
            'rangeindex' => '6',
            'nameEnglish' => 'Moss green',
            'nameGerman' => 'Moosgrün',
            'hex' => '0F4336',
        ],
        [
            'number' => 'RAL 6006',
            'rangeindex' => '6',
            'nameEnglish' => 'Grey olive',
            'nameGerman' => 'Grauoliv',
            'hex' => '40433B',
        ],
        [
            'number' => 'RAL 6007',
            'rangeindex' => '6',
            'nameEnglish' => 'Bottle green',
            'nameGerman' => 'Flaschengrün',
            'hex' => '283424',
        ],
        [
            'number' => 'RAL 6008',
            'rangeindex' => '6',
            'nameEnglish' => 'Brown green',
            'nameGerman' => 'Braungrün',
            'hex' => '35382E',
        ],
        [
            'number' => 'RAL 6009',
            'rangeindex' => '6',
            'nameEnglish' => 'Fir green',
            'nameGerman' => 'Tannengrün',
            'hex' => '26392F',
        ],
        [
            'number' => 'RAL 6010',
            'rangeindex' => '6',
            'nameEnglish' => 'Grass green',
            'nameGerman' => 'Grasgrün',
            'hex' => '3E753B',
        ],
        [
            'number' => 'RAL 6011',
            'rangeindex' => '6',
            'nameEnglish' => 'Reseda green',
            'nameGerman' => 'Resedagrün',
            'hex' => '68825B',
        ],
        [
            'number' => 'RAL 6012',
            'rangeindex' => '6',
            'nameEnglish' => 'Black green',
            'nameGerman' => 'Schwarzgrün',
            'hex' => '31403D',
        ],
        [
            'number' => 'RAL 6013',
            'rangeindex' => '6',
            'nameEnglish' => 'Reed green',
            'nameGerman' => 'Schilfgrün',
            'hex' => '797C5A',
        ],
        [
            'number' => 'RAL 6014',
            'rangeindex' => '6',
            'nameEnglish' => 'Yellow olive',
            'nameGerman' => 'Gelboliv',
            'hex' => '444337',
        ],
        [
            'number' => 'RAL 6015',
            'rangeindex' => '6',
            'nameEnglish' => 'Black olive',
            'nameGerman' => 'Schwarzoliv',
            'hex' => '3D403A',
        ],
        [
            'number' => 'RAL 6016',
            'rangeindex' => '6',
            'nameEnglish' => 'Turquoise green',
            'nameGerman' => 'Türkisgrün',
            'hex' => '026A52',
        ],
        [
            'number' => 'RAL 6017',
            'rangeindex' => '6',
            'nameEnglish' => 'May green',
            'nameGerman' => 'Maigrün',
            'hex' => '468641',
        ],
        [
            'number' => 'RAL 6018',
            'rangeindex' => '6',
            'nameEnglish' => 'Yellow green',
            'nameGerman' => 'Gelbgrün',
            'hex' => '48A43F',
        ],
        [
            'number' => 'RAL 6019',
            'rangeindex' => '6',
            'nameEnglish' => 'pastel green',
            'nameGerman' => 'Weißgrün',
            'hex' => 'B7D9B1',
        ],
        [
            'number' => 'RAL 6020',
            'rangeindex' => '6',
            'nameEnglish' => 'Chrome green',
            'nameGerman' => 'Chromoxidgrün',
            'hex' => '354733',
        ],
        [
            'number' => 'RAL 6021',
            'rangeindex' => '6',
            'nameEnglish' => 'Pale green',
            'nameGerman' => 'Blassgrün',
            'hex' => '86A47C',
        ],
        [
            'number' => 'RAL 6022',
            'rangeindex' => '6',
            'nameEnglish' => 'Brown olive',
            'nameGerman' => 'Braunoliv',
            'hex' => '3E3C32',
        ],
        [
            'number' => 'RAL 6024',
            'rangeindex' => '6',
            'nameEnglish' => 'Traffic green',
            'nameGerman' => 'Verkehrsgrün',
            'hex' => '8754',
        ],
        [
            'number' => 'RAL 6025',
            'rangeindex' => '6',
            'nameEnglish' => 'Fern green',
            'nameGerman' => 'Farngrün',
            'hex' => '53753C',
        ],
        [
            'number' => 'RAL 6026',
            'rangeindex' => '6',
            'nameEnglish' => 'Opal green',
            'nameGerman' => 'Opalgrün',
            'hex' => '005D52',
        ],
        [
            'number' => 'RAL 6027',
            'rangeindex' => '6',
            'nameEnglish' => 'Light green',
            'nameGerman' => 'Lichtgrün',
            'hex' => '81C0BB',
        ],
        [
            'number' => 'RAL 6028',
            'rangeindex' => '6',
            'nameEnglish' => 'Pine green',
            'nameGerman' => 'Kieferngrün',
            'hex' => '2D5546',
        ],
        [
            'number' => 'RAL 6029',
            'rangeindex' => '6',
            'nameEnglish' => 'Mint green',
            'nameGerman' => 'Minzgrün',
            'hex' => '7243',
        ],
        [
            'number' => 'RAL 6032',
            'rangeindex' => '6',
            'nameEnglish' => 'Signal green',
            'nameGerman' => 'Signalgrün',
            'hex' => '0F8558',
        ],
        [
            'number' => 'RAL 6033',
            'rangeindex' => '6',
            'nameEnglish' => 'Mint turquoise',
            'nameGerman' => 'Minttürkis',
            'hex' => '478A84',
        ],
        [
            'number' => 'RAL 6034',
            'rangeindex' => '6',
            'nameEnglish' => 'Pastel turquoise',
            'nameGerman' => 'Pastelltürkis',
            'hex' => '7FB0B2',
        ],
        [
            'number' => 'RAL 6035',
            'rangeindex' => '6',
            'nameEnglish' => 'Pearl green',
            'nameGerman' => 'Perlgrün',
            'hex' => '1B542C',
        ],
        [
            'number' => 'RAL 6036',
            'rangeindex' => '6',
            'nameEnglish' => 'Pearl opal green',
            'nameGerman' => 'Perlopalgrün',
            'hex' => '005D4C',
        ],
        [
            'number' => 'RAL 6037',
            'rangeindex' => '6',
            'nameEnglish' => 'Pure green',
            'nameGerman' => 'Reingrün',
            'hex' => '25E712',
        ],
        [
            'number' => 'RAL 6038',
            'rangeindex' => '6',
            'nameEnglish' => 'Luminous green',
            'nameGerman' => 'Leuchtgrün',
            'hex' => '00F700',
        ],
        [
            'number' => 'RAL 7000',
            'rangeindex' => '7',
            'nameEnglish' => 'Squirrel grey',
            'nameGerman' => 'Fehgrau',
            'hex' => '7E8B92',
        ],
        [
            'number' => 'RAL 7001',
            'rangeindex' => '7',
            'nameEnglish' => 'Silver grey',
            'nameGerman' => 'Silbergrau',
            'hex' => '8F999F',
        ],
        [
            'number' => 'RAL 7002',
            'rangeindex' => '7',
            'nameEnglish' => 'Olive grey',
            'nameGerman' => 'Olivgrau',
            'hex' => '817F68',
        ],
        [
            'number' => 'RAL 7003',
            'rangeindex' => '7',
            'nameEnglish' => 'Moss grey',
            'nameGerman' => 'Moosgrau',
            'hex' => '7A7B6D',
        ],
        [
            'number' => 'RAL 7004',
            'rangeindex' => '7',
            'nameEnglish' => 'Signal grey',
            'nameGerman' => 'Signalgrau',
            'hex' => '9EA0A1',
        ],
        [
            'number' => 'RAL 7005',
            'rangeindex' => '7',
            'nameEnglish' => 'Mouse grey',
            'nameGerman' => 'Mausgrau',
            'hex' => '6B716F',
        ],
        [
            'number' => 'RAL 7006',
            'rangeindex' => '7',
            'nameEnglish' => 'Beige grey',
            'nameGerman' => 'Beigegrau',
            'hex' => '756F61',
        ],
        [
            'number' => 'RAL 7008',
            'rangeindex' => '7',
            'nameEnglish' => 'Khaki grey',
            'nameGerman' => 'Khakigrau',
            'hex' => '746643',
        ],
        [
            'number' => 'RAL 7009',
            'rangeindex' => '7',
            'nameEnglish' => 'Green grey',
            'nameGerman' => 'Grüngrau',
            'hex' => '5B6259',
        ],
        [
            'number' => 'RAL 7010',
            'rangeindex' => '7',
            'nameEnglish' => 'Tarpaulin grey',
            'nameGerman' => 'Zeltgrau',
            'hex' => '575D57',
        ],
        [
            'number' => 'RAL 7011',
            'rangeindex' => '7',
            'nameEnglish' => 'Iron grey',
            'nameGerman' => 'Eisengrau',
            'hex' => '555D61',
        ],
        [
            'number' => 'RAL 7012',
            'rangeindex' => '7',
            'nameEnglish' => 'Basalt grey',
            'nameGerman' => 'Basaltgrau',
            'hex' => '596163',
        ],
        [
            'number' => 'RAL 7013',
            'rangeindex' => '7',
            'nameEnglish' => 'Brown-grey also NATO-olive also Stone-grey-olive',
            'nameGerman' => 'Braungrau auch NATO-oliv auch Steingrau-olive',
            'hex' => '555548',
        ],
        [
            'number' => 'RAL 7015',
            'rangeindex' => '7',
            'nameEnglish' => 'Slate grey',
            'nameGerman' => 'Schiefergrau',
            'hex' => '51565C',
        ],
        [
            'number' => 'RAL 7016',
            'rangeindex' => '7',
            'nameEnglish' => 'Anthracite grey',
            'nameGerman' => 'Anthrazitgrau',
            'hex' => '373F43',
        ],
        [
            'number' => 'RAL 7021',
            'rangeindex' => '7',
            'nameEnglish' => 'Black grey',
            'nameGerman' => 'Schwarzgrau',
            'hex' => '2E3234',
        ],
        [
            'number' => 'RAL 7022',
            'rangeindex' => '7',
            'nameEnglish' => 'Umbra grey',
            'nameGerman' => 'Umbragrau',
            'hex' => '4B4D46',
        ],
        [
            'number' => 'RAL 7023',
            'rangeindex' => '7',
            'nameEnglish' => 'Concrete grey',
            'nameGerman' => 'Betongrau',
            'hex' => '818479',
        ],
        [
            'number' => 'RAL 7024',
            'rangeindex' => '7',
            'nameEnglish' => 'Graphite grey',
            'nameGerman' => 'Graphitgrau',
            'hex' => '474A50',
        ],
        [
            'number' => 'RAL 7026',
            'rangeindex' => '7',
            'nameEnglish' => 'Granite grey',
            'nameGerman' => 'Granitgrau',
            'hex' => '374447',
        ],
        [
            'number' => 'RAL 7030',
            'rangeindex' => '7',
            'nameEnglish' => 'Stone grey',
            'nameGerman' => 'Steingrau',
            'hex' => '939388',
        ],
        [
            'number' => 'RAL 7031',
            'rangeindex' => '7',
            'nameEnglish' => 'Blue grey',
            'nameGerman' => 'Blaugrau',
            'hex' => '5D6970',
        ],
        [
            'number' => 'RAL 7032',
            'rangeindex' => '7',
            'nameEnglish' => 'Pebble grey',
            'nameGerman' => 'Kieselgrau',
            'hex' => 'B9B9A8',
        ],
        [
            'number' => 'RAL 7033',
            'rangeindex' => '7',
            'nameEnglish' => 'Cement grey',
            'nameGerman' => 'Zementgrau',
            'hex' => '818979',
        ],
        [
            'number' => 'RAL 7034',
            'rangeindex' => '7',
            'nameEnglish' => 'Yellow grey',
            'nameGerman' => 'Gelbgrau',
            'hex' => '939176',
        ],
        [
            'number' => 'RAL 7035',
            'rangeindex' => '7',
            'nameEnglish' => 'Light grey',
            'nameGerman' => 'Lichtgrau',
            'hex' => 'CBD0CC',
        ],
        [
            'number' => 'RAL 7036',
            'rangeindex' => '7',
            'nameEnglish' => 'Platinum grey',
            'nameGerman' => 'Platingrau',
            'hex' => '9A9697',
        ],
        [
            'number' => 'RAL 7037',
            'rangeindex' => '7',
            'nameEnglish' => 'Dusty grey',
            'nameGerman' => 'Staubgrau',
            'hex' => '7C7F7E',
        ],
        [
            'number' => 'RAL 7038',
            'rangeindex' => '7',
            'nameEnglish' => 'Agate grey',
            'nameGerman' => 'Achatgrau',
            'hex' => 'B4B8B0',
        ],
        [
            'number' => 'RAL 7039',
            'rangeindex' => '7',
            'nameEnglish' => 'Quartz grey',
            'nameGerman' => 'Quarzgrau',
            'hex' => '6B695F',
        ],
        [
            'number' => 'RAL 7040',
            'rangeindex' => '7',
            'nameEnglish' => 'Window grey',
            'nameGerman' => 'Fenstergrau',
            'hex' => '9DA3A6',
        ],
        [
            'number' => 'RAL 7042',
            'rangeindex' => '7',
            'nameEnglish' => 'Traffic grey A',
            'nameGerman' => 'Verkehrsgrau A',
            'hex' => '8F9695',
        ],
        [
            'number' => 'RAL 7043',
            'rangeindex' => '7',
            'nameEnglish' => 'Traffic grey B',
            'nameGerman' => 'Verkehrsgrau B',
            'hex' => '4E5451',
        ],
        [
            'number' => 'RAL 7044',
            'rangeindex' => '7',
            'nameEnglish' => 'Silk grey',
            'nameGerman' => 'Seidengrau',
            'hex' => 'BDBDB2',
        ],
        [
            'number' => 'RAL 7045',
            'rangeindex' => '7',
            'nameEnglish' => 'Telegrey 1',
            'nameGerman' => 'Telegrau 1',
            'hex' => '91969A',
        ],
        [
            'number' => 'RAL 7046',
            'rangeindex' => '7',
            'nameEnglish' => 'Telegrey 2',
            'nameGerman' => 'Telegrau 2',
            'hex' => '82898E',
        ],
        [
            'number' => 'RAL 7047',
            'rangeindex' => '7',
            'nameEnglish' => 'Telegrey 4',
            'nameGerman' => 'Telegrau 4',
            'hex' => 'CFD0CF',
        ],
        [
            'number' => 'RAL 7048',
            'rangeindex' => '7',
            'nameEnglish' => 'Pearl mouse grey',
            'nameGerman' => 'Perlmausgrau',
            'hex' => '888175',
        ],
        [
            'number' => 'RAL 8000',
            'rangeindex' => '8',
            'nameEnglish' => 'Green brown',
            'nameGerman' => 'Grünbraun',
            'hex' => '887142',
        ],
        [
            'number' => 'RAL 8001',
            'rangeindex' => '8',
            'nameEnglish' => 'Ochre brown',
            'nameGerman' => 'Ockerbraun',
            'hex' => '9C6B30',
        ],
        [
            'number' => 'RAL 8002',
            'rangeindex' => '8',
            'nameEnglish' => 'Signal brown',
            'nameGerman' => 'Signalbraun',
            'hex' => '7B5141',
        ],
        [
            'number' => 'RAL 8003',
            'rangeindex' => '8',
            'nameEnglish' => 'Clay brown',
            'nameGerman' => 'Lehmbraun',
            'hex' => '80542F',
        ],
        [
            'number' => 'RAL 8004',
            'rangeindex' => '8',
            'nameEnglish' => 'Copper brown',
            'nameGerman' => 'Kupferbraun',
            'hex' => '8F4E35',
        ],
        [
            'number' => 'RAL 8007',
            'rangeindex' => '8',
            'nameEnglish' => 'Fawn brown',
            'nameGerman' => 'Rehbraun',
            'hex' => '6F4A2F',
        ],
        [
            'number' => 'RAL 8008',
            'rangeindex' => '8',
            'nameEnglish' => 'Olive brown',
            'nameGerman' => 'Olivbraun',
            'hex' => '6F4F28',
        ],
        [
            'number' => 'RAL 8011',
            'rangeindex' => '8',
            'nameEnglish' => 'Nut brown',
            'nameGerman' => 'Nussbraun',
            'hex' => '5A3A29',
        ],
        [
            'number' => 'RAL 8012',
            'rangeindex' => '8',
            'nameEnglish' => 'Red brown',
            'nameGerman' => 'Rotbraun',
            'hex' => '673831',
        ],
        [
            'number' => 'RAL 8014',
            'rangeindex' => '8',
            'nameEnglish' => 'Sepia brown',
            'nameGerman' => 'Sepiabraun',
            'hex' => '49392D',
        ],
        [
            'number' => 'RAL 8015',
            'rangeindex' => '8',
            'nameEnglish' => 'Chestnut brown',
            'nameGerman' => 'Kastanienbraun',
            'hex' => '633A34',
        ],
        [
            'number' => 'RAL 8016',
            'rangeindex' => '8',
            'nameEnglish' => 'Mahogany brown',
            'nameGerman' => 'Mahagonibraun',
            'hex' => '4C2F26',
        ],
        [
            'number' => 'RAL 8017',
            'rangeindex' => '8',
            'nameEnglish' => 'Chocolate brown',
            'nameGerman' => 'Schokoladenbraun',
            'hex' => '44322D',
        ],
        [
            'number' => 'RAL 8019',
            'rangeindex' => '8',
            'nameEnglish' => 'Grey brown',
            'nameGerman' => 'Graubraun',
            'hex' => '3F3A3A',
        ],
        [
            'number' => 'RAL 8022',
            'rangeindex' => '8',
            'nameEnglish' => 'Black brown',
            'nameGerman' => 'Schwarzbraun',
            'hex' => '211F20',
        ],
        [
            'number' => 'RAL 8023',
            'rangeindex' => '8',
            'nameEnglish' => 'Orange brown',
            'nameGerman' => 'Orangebraun',
            'hex' => 'A65E2F',
        ],
        [
            'number' => 'RAL 8024',
            'rangeindex' => '8',
            'nameEnglish' => 'Beige brown',
            'nameGerman' => 'Beigebraun',
            'hex' => '79553C',
        ],
        [
            'number' => 'RAL 8025',
            'rangeindex' => '8',
            'nameEnglish' => 'Pale brown',
            'nameGerman' => 'Blassbraun',
            'hex' => '755C49',
        ],
        [
            'number' => 'RAL 8028',
            'rangeindex' => '8',
            'nameEnglish' => 'Terra brown',
            'nameGerman' => 'Terrabraun',
            'hex' => '4E3B2B',
        ],
        [
            'number' => 'RAL 8029',
            'rangeindex' => '8',
            'nameEnglish' => 'Pearl copper',
            'nameGerman' => 'Perlkupfer',
            'hex' => '773C27',
        ],
        [
            'number' => 'RAL 9001',
            'rangeindex' => '9',
            'nameEnglish' => 'Cream',
            'nameGerman' => 'Cremeweiß',
            'hex' => 'EFEBDC',
        ],
        [
            'number' => 'RAL 9002',
            'rangeindex' => '9',
            'nameEnglish' => 'Grey white',
            'nameGerman' => 'Grauweiß',
            'hex' => 'DDDED4',
        ],
        [
            'number' => 'RAL 9003',
            'rangeindex' => '9',
            'nameEnglish' => 'Signal white',
            'nameGerman' => 'Signalweiß',
            'hex' => 'F4F8F4',
        ],
        [
            'number' => 'RAL 9004',
            'rangeindex' => '9',
            'nameEnglish' => 'Signal black',
            'nameGerman' => 'Signalschwarz',
            'hex' => '2E3032',
        ],
        [
            'number' => 'RAL 9005',
            'rangeindex' => '9',
            'nameEnglish' => 'Jet black',
            'nameGerman' => 'Tiefschwarz',
            'hex' => '0A0A0D',
        ],
        [
            'number' => 'RAL 9006',
            'rangeindex' => '9',
            'nameEnglish' => 'White aluminium',
            'nameGerman' => 'Weißaluminium',
            'hex' => 'A5A8A6',
        ],
        [
            'number' => 'RAL 9007',
            'rangeindex' => '9',
            'nameEnglish' => 'Grey aluminium',
            'nameGerman' => 'Graualuminium',
            'hex' => '8F8F8C',
        ],
        [
            'number' => 'RAL 9010',
            'rangeindex' => '9',
            'nameEnglish' => 'Pure white',
            'nameGerman' => 'Reinweiß',
            'hex' => 'F7F9EF',
        ],
        [
            'number' => 'RAL 9011',
            'rangeindex' => '9',
            'nameEnglish' => 'Graphite black',
            'nameGerman' => 'Graphitschwarz',
            'hex' => '292C2F',
        ],
        [
            'number' => 'RAL 9016',
            'rangeindex' => '9',
            'nameEnglish' => 'Traffic white',
            'nameGerman' => 'Verkehrsweiß',
            'hex' => 'F7FBF5',
        ],
        [
            'number' => 'RAL 9017',
            'rangeindex' => '9',
            'nameEnglish' => 'Traffic black',
            'nameGerman' => 'Verkehrsschwarz',
            'hex' => '2A2D2F',
        ],
        [
            'number' => 'RAL 9018',
            'rangeindex' => '9',
            'nameEnglish' => 'Papyrus white',
            'nameGerman' => 'Papyrusweiß',
            'hex' => 'CFD3CD',
        ],
        [
            'number' => 'RAL 9022',
            'rangeindex' => '9',
            'nameEnglish' => 'Pearl light grey',
            'nameGerman' => 'Perlhellgrau',
            'hex' => '9C9C9C',
        ],
        [
            'number' => 'RAL 9023',
            'rangeindex' => '9',
            'nameEnglish' => 'Pearl dark grey',
            'nameGerman' => 'Perldunkelgrau',
            'hex' => '7E8182',
        ],
    ];

    /**
     * The range index of the RAL Classic Colors
     *
     * @var array
     */
    protected $ranges = [
        1 => [
            'rangeindex' => '1',
            'nameEnglish' => 'Yellow and beige',
            'nameGerman' => 'Gelb und Beige',
        ],
        2 => [
            'rangeindex' => '2',
            'nameEnglish' => 'Orange',
            'nameGerman' => 'Orange',
        ],
        3 => [
            'rangeindex' => '3',
            'nameEnglish' => 'Red',
            'nameGerman' => 'Rot',
        ],
        4 => [
            'rangeindex' => '4',
            'nameEnglish' => 'Violet',
            'nameGerman' => 'Violett',
        ],
        5 => [
            'rangeindex' => '5',
            'nameEnglish' => 'Blue',
            'nameGerman' => 'Blau',
        ],
        6 => [
            'rangeindex' => '6',
            'nameEnglish' => 'Green',
            'nameGerman' => 'Grün',
        ],
        7 => [
            'rangeindex' => '7',
            'nameEnglish' => 'Grey',
            'nameGerman' => 'Grau',
        ],
        8 => [
            'rangeindex' => '8',
            'nameEnglish' => 'Brown',
            'nameGerman' => 'Braun',
        ],
        9 => [
            'rangeindex' => '9',
            'nameEnglish' => 'White and Black',
            'nameGerman' => 'Weiß und Schwarz',
        ]
    ];

    /**
     * Returns the list of RAL Classic Colors
     *
     * @return array
     */
    public function getList(): array
    {
        return $this->colors;
    }

    /**
     * Returns the list of RAL Classic Colors grouped by range index
     *
     * @return array
     */
    public function getGroupedList(): array
    {
        return $this->groupArray($this->colors, 'rangeindex');
    }

    /**
     * Return a single RAL Classic Color
     *
     * @param string $numberCode Number code of the RAL color, eg. "RAL 2010"
     * @return array Is empty if no matching color is found
     */
    public function getSingleColor($numberCode = ''): array
    {
        $key = array_search($numberCode, array_column($this->colors, 'number'), true) ?: null;
        return $this->colors[$key] ?? [];
    }

    /**
     * Returns the list of RAL Classic Ranges
     *
     * @return array
     */
    public function getRangeList(): array
    {
        return $this->ranges;
    }

    /**
     * Group an array of associative arrays by some key
     *
     * @param array $associativeArray Array that stores multiple associative arrays
     * @param string $groupByKey Property to sort by
     */
    public function groupArray(array $associativeArray, string $groupByKey): array
    {
        $result = array();

        foreach ($associativeArray as $array) {
            if (array_key_exists($groupByKey, $array)) {
                $result[$array[$groupByKey]][] = $array;
            } else {
                $result[''][] = $array;
            }
        }

        return $result;
    }
}
